// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydmuparasfqlplbkktto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbXVwYXJhc2ZxbHBsYmtrdHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDA2OTMsImV4cCI6MjA3MzY3NjY5M30.MF9j4Sg_0AfwmsbuOhT-g2i13X-NfN4kOseJRpkD9Qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});